# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=test@123
    volumes:
       - db-data:/var/lib/mysql/data
    ports:
      - 1401:1433
  mvcwebapp:
    image: mvcwebapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
volumes:
  db-data: